/**
 * Verification Session
 * 
 * Represents a verification session created by the backend.
 * Contains the OAuth2 authorization request URL and state for SSE tracking.
 * 
 * **Flow:**
 * 1. Backend generates authRequest (openid4vp:// URL) via OAuth2 flow
 * 2. PWA displays authRequest as QR code
 * 3. Wallet scans QR and submits VP to backend
 * 4. Backend validates and emits SSE event with state
 * 5. PWA receives event and displays result
 * 
 * @interface VerificationSession
 */
export interface VerificationSession {
  /**
   * Authorization request URL (openid4vp:// protocol)
   * Contains the full OAuth2 authorization request with JWT
   * Ready to be displayed as QR code
   */
  authRequest: string;

  /**
   * OAuth2 state parameter
   * Used to correlate SSE events with this session
   */
  state: string;

  /**
   * Session identifier (nonce)
   * Generated by backend, used for session tracking
   */
  sessionId: string;
}

